"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#$7^d@ts&0rw*l@@uc3a%2r8-um-$guugzp))4em$qs&mcz&h$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Editado para configuración de correo electronico
EMAIL_HOST = 'smtp.live.com'
EMAIL_HOST_USER = 'fjgh.777@hotmail.com'
EMAIL_HOST_PASSWORD = '*****'
EMAIL_PORT = 25
EMAIL_USE_TLS = True

'''Para usar gmail hay que desbloquear el captcha
https://acounts.google.com/displayunlockcaptcha
'''

# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.sites', #redux
    'registration', #redux
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apss de terceros
    'crispy_forms',
    
    # Mis apps
    'blog.apps.BlogConfig',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/' # archivos como css, js
STATIC_URL = '/media/' # archivos de imagenes, videos, audio

# En esta sección tendremos nuestros archivos estaticos

# Hemos creado 1 carpeta para el proyecto llamada static_pro (a nivel de manage.py) y dentro de ella la carpeta static.
# BASE_DIR corresponde a la carpeta del proyecto. cuando utilizamos os.path.join, es como si cada elemento que este entre parentesis
# lo separaramos con / especificando ruta (BASE_DIR/static_pro/static)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_pro', 'static'),
]

# En esta sección se crea la carpeta de ambiente de desarrollo y se crea fuera de la carpeta del proyecto (../django_project) al igual
# que el media. con os.path.dirname estamos direccionando los archivos al directorio padre del proyecto 
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static_env', 'static_root')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static_env' 'media_root')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.
CRISPY_TEMPLATE_PACK = 'bootstrap4'